---
- name: Provision instance
  ec2:
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    region: "{{ AWS_REGION }}"
    instance_type: "{{ micro }}"
    image: "{{ rhel8 }}"
    assign_public_ip: yes
    vpc_subnet_id: "{{ subnet_id }}"
    wait: true
    exact_count: 2
    count_tag:
      Name: test1
    instance_tags:
      Name: test1
    key_name: ansible

# - name: Output IP addresses of instance
#   debug:
#     msg: "IP address: {{ item.public_ip }}"
#   loop: "{{ ec2.instances }}"

# - name: add host to inventory
#   add_host:
#     hostname: "{{item.public_ip }}"
#     groupname: test1
#     ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
#     ansible-ssh_private_key_file: ~/.ssh/ansible.pem
#   loop: "{{ ec2.instances }}"

# - name: register new instance IDs
#   ec2_metadata_facts: 
#   register: ec2_meta_facts

# - name: Checkout gathered facts
#   debug:
#     var: hostvars[groups['test1'][0..1]]['ansible_ec2_instance_id']
#   register: instance_ids

# Need to figure out a way to dynamically update {{ instance_ids }}
# I can get it to work in a playbook file but want to in a role.

- name: Create alarm
  ec2_metric_alarm:
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    region: "{{ AWS_REGION }}"
    state: present
    name: "high-cpu"
    metric: "CPUUtilization"
    namespace: "AWS/EC2"
    statistic: Average
    comparison: ">="
    threshold: 90.0
    period: 300
    evaluation_periods: 3
    unit: "Percent"
    dimensions: "{'InstanceId':'{{ instance_ids }}"
  