---
- name: Provision instance
  ec2:
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    region: "{{ AWS_REGION }}"
    instance_type: "{{ micro }}"
    image: "{{ rhel8 }}"
    assign_public_ip: yes
    vpc_subnet_id: "{{ subnet_id }}"
    wait: true
    exact_count: 2
    count_tag:
      Name: test
    key_name: ansible