---
- name: Get instances
  ec2_instance_facts:
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECRET_KEY }}"
    region: "{{ AWS_REGION }}"
    # filter:
  register: ec2_facts

- debug:
    var: ec2_facts
