---
- hosts: localhost
  gather_facts: true
  vars_files:
    - ../keys.yml
  
  tasks:
    - name: Chantge instances state by tag
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        region: "{{ AWS_REGION }}"
        state: running
        wait: yes
        instance_tags:
          Name: test
      register: ec2

    - name: Output IP addresses of instance
      debug:
        msg: "IP address: {{ item.public_ip }}"
      loop: "{{ ec2.instances }}"

    - name: add host to inventory
      add_host:
        hostname: "{{item.public_ip }}"
        groupname: test
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ansible-ssh_private_key_file: ~/.ssh/ansible.pem
      loop: "{{ ec2.instances }}"

- hosts: test
  gather_facts: false
  remote_user: ec2-user
  tasks:
  
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 5
        timeout: 30

    - name: Collect instance facts
      ec2_metadata_facts:
      register: ec2_meta_facts

- hosts: localhost
  gather_facts: yes
  vars_files: 
    - ../keys.yml
  
  tasks:
    - name: Checkout gathered facts
      debug:
        var: hostvars[groups['test'][0]]['ansible_ec2_instance_id']
      
    - name: Change instances state by tag
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        region: "{{ AWS_REGION }}"
        state: stopped